import Field from '../ui/Field'

export const EMPTY_DVD_FORM = {
  title: '', magician: '', magicType: '', producer: '', year: '', otherFeatures: '', notes: '',
  vanishingIncUrl: '', penguinUrl: '', conjuringArchiveUrl: '', featured: false, aiSummary: '',
}

export function dvdToForm(dvd = {}) {
  const list = value => Array.isArray(value) ? value.join('; ') : String(value || '')
  return {
    ...EMPTY_DVD_FORM,
    ...dvd,
    magician: list(dvd.magician),
    magicType: list(dvd.magicType),
    otherFeatures: list(dvd.otherFeatures),
    featured: dvd.featured === true,
    aiSummary: String(dvd.aiSummary || ''),
  }
}

export default function DVDForm({ value, onChange, errors = {} }) {
  const set = field => event => onChange({ ...value, [field]: event.target.type === 'checkbox' ? event.target.checked : event.target.value })
  const input = (field, label, options = {}) => <Field label={label} error={errors[field]} hint={options.hint} required={options.required}>
    {props => options.textarea
      ? <textarea {...props} className="input" rows={options.rows || 4} value={value[field]} onChange={set(field)} />
      : <input {...props} className="input" type={options.type || 'text'} inputMode={options.inputMode} required={options.required} value={value[field]} onChange={set(field)} />}
  </Field>

  return <div className="dvd-form-grid">
    <div className="field-span-2">{input('title', 'Title', { required: true })}</div>
    {input('magician', 'Magician / performer', { hint: 'Separate multiple names with semicolons.' })}
    {input('magicType', 'Magic type', { hint: 'For example: Cards; Coins; Mentalism' })}
    {input('producer', 'Producer')}
    {input('year', 'Year released', { inputMode: 'numeric' })}
    <div className="field-span-2">{input('otherFeatures', 'Also featuring', { hint: 'Separate multiple names or features with semicolons.' })}</div>
    <div className="field-span-2">{input('notes', 'Contents and notes', { textarea: true, rows: 5 })}</div>
    <div className="field-span-2">{input('aiSummary', 'AI Summary', { textarea: true, rows: 4, hint: 'Summary generated by Claude. You can refine or edit this text directly.' })}</div>
    {input('vanishingIncUrl', 'Vanishing Inc. link', { type: 'url' })}
    {input('penguinUrl', 'Penguin Magic link', { type: 'url' })}
    <div className="field-span-2">{input('conjuringArchiveUrl', 'Conjuring Archive link', { type: 'url' })}</div>
    <label className="feature-toggle field-span-2">
      <input type="checkbox" checked={value.featured} onChange={set('featured')} />
      <span><strong>Featured title</strong><small>Give this DVD extra prominence in the public catalog.</small></span>
    </label>
  </div>
}
